language: node_js
node_js:
  - node

services:
  - mongodb


before_install:
  - cd ${TRAVIS_BUILD_DIR}/Backend

install:
  - npm install travis_retry 
  - npm install jest --save
  - npm install supertest --save
  - npm install @babel/core --save
  - npm install babel-jest --save
  - npm install @babel/preset-env --save
  - npm install socket.io --save
  - npm install mongoose --save



  
script:
  - npm run test
