language: node_js
node_js:
  - node

services:
  - mongodb

install:
  - travis_retry npm install

before_script:
  - cd ${TRAVIS_BUILD_DIR}/Backend
  - npm install jest --save
  - npm install supertest --save
  - npm install @babel/core --save
  - npm install babel-jest --save
  - npm install @babel/preset-env --save
  - npm install socket.io --save
  - npm install mongoose --save

  
script:
  - npm run test
