dist: trusty

matrix:
include:
- language: node_js
node_js:
- node
services:
- mongodb
before_script:
- cd ${TRAVIS_BUILD_DIR}/Backend
- npm install
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_bd11dfdabef3_key -iv $encrypted_bd11dfdabef3_iv -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar

-language: android

components:
  - tools
  - platform-tools
  # The BuildTools version used by your project
  - build-tools-29.0.3
  # The SDK version used to compile your project
  - android-29
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL

# Specify at least one system image,
# if you need to run emulator(s) during your tests
#- sys-img-x86-android-26
#- sys-img-armeabi-v7a-android-17
licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
      
services:
- mongodb
before_script:
- mkdir -p "$ANDROID_HOME/licenses"
- cp ./Frontend/* "$ANDROID_HOME/licenses/"
script:
- ./Frontend/gradle build connectedCheck
