language: node_js
node_js:
- node
services:
- mongodb
before_script:
- cd ${TRAVIS_BUILD_DIR}/Backend
- npm install
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_bd11dfdabef3_key -iv $encrypted_bd11dfdabef3_iv -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
