language: node_js
node_js:
- node
services:
- mongodb
before_script:
- cd ${TRAVIS_BUILD_DIR}/Backend
- npm install
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_0b0d3c85d8df_key -iv $encrypted_0b0d3c85d8df_iv
  -in google-services.json.enc -out Frontend/app/google-services.json -d
